using RoconMqtt.Api;
using RoconMqtt.Can.Extensions.DependencyInjection;
using RoconMqtt.Mqtt.Extensions.DependencyInjection;
using Serilog;
using System.Text.Json;

namespace RoconMqtt;

public static class Program
{
    private static async Task Main(string[] args)
    {
        var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production";
        
        Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(
                new ConfigurationBuilder()
                    .AddJsonFile("appsettings.json")
                    .AddJsonFile($"appsettings.{environment}.json", optional: true)
                    .Build()
            )
            .CreateLogger();

        try
        {
            var builder = WebApplication.CreateBuilder(args);
            
            builder.Host.UseSerilog();

            // Configure CAN service
            builder.Services.AddCanService(builder.Configuration)
                //.WithSocketCanBus();
                //.WithSshCanBus();
                .WithAutoCanBus();

            // Configure MQTT services
            builder.Services.AddMqttService(builder.Configuration);

            // Configure OpenAPI document generation (Microsoft native)
            builder.Services.AddOpenApi(options =>
            {
                options.AddDocumentTransformer((document, context, ct) =>
                {
                    document.Info.Title = "Rocon MQTT API";
                    document.Info.Version = "v1";
                    document.Info.Description = "REST API for Rotex Rocon G1 heating controller communication over CAN bus";
                    return Task.CompletedTask;
                });
            });

            // Configure JSON serialization with STJ source generation for Linux ARM64
            builder.Services.ConfigureHttpJsonOptions(o =>
            {
                o.SerializerOptions.TypeInfoResolverChain.Insert(0, ApiJsonContext.Default);
            });

            var app = builder.Build();

            // Configure middleware
            app.UseSerilogRequestLogging();

            // Map OpenAPI document endpoint (generated by Microsoft.AspNetCore.OpenApi)
            app.MapOpenApi();

            // Enable Swagger UI (only UI, consuming the OpenAPI document above)
            app.UseSwaggerUI(options =>
            {
                options.DocumentTitle = "Rocon MQTT API";
                options.SwaggerEndpoint("/openapi/v1.json", "Rocon MQTT API v1");
            });

            // Map API endpoints
            app.MapApiEndpoints();

            // Redirect root to Swagger UI
            app.MapGet("/", () => Results.Redirect("/swagger", permanent: false))
                .ExcludeFromDescription();

            await app.RunAsync();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Application terminated unexpectedly");
        }
        finally
        {
            await Log.CloseAndFlushAsync();
        }
    }
}